//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Medico
    {
        public int id_medico { get; set; }
        public Nullable<int> id_especialidade { get; set; }

        [Required(ErrorMessage = "Obrigatorio informar crm")]
        public string crm { get; set; }

        [Required(ErrorMessage = "Obrigatorio informar email")]
        public string email { get; set; }

        [Required(ErrorMessage = "Obrigatorio informar nome")]
        public string nome { get; set; }

        [Required(ErrorMessage = "Obrigatorio informar endereço")]
        public string endereco { get; set; }

        [Required(ErrorMessage = "Obrigatorio informar bairro")]
        public string bairro { get; set; }

        public Nullable<int> id_cidade { get; set; }

       

        public Nullable<bool> atende_por_convenio { get; set; }
        public Nullable<bool> tem_clinica { get; set; }

        [Required(ErrorMessage = "Obrigatorio informar website")]
        public string web_site_blog { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Especialidade Especialidade { get; set; }
    }
}
