//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int id_usuario { get; set; }
        [Required(ErrorMessage = "Obrigatorio informar nome")]
        public string nome { get; set; }

        [Required(ErrorMessage = "Obrigatorio informar usuario")]
        public string usuario1 { get; set; }

        [Required(ErrorMessage = "Obrigatorio informar senha")]
        public string senha { get; set; }

        [Required(ErrorMessage = "Obrigatorio informar email")]
        public string email { get; set; }
    }
}
